### ISSUE TITLE
Espejo does not ignore everything defined in ignoreNames array

### ISSUE THREAD

**Issue by ZuGao** [vshn/espejo#107]
## Describe the bug

Some regex entries in _ignoreNames_ list are not being enforced.

## Additional context

Espejo does not ignore "csl-*" namespaces in an OpenShift cluster with the following ignoreNames list:
```yml
namespaceSelector:
  ignoreNames:
  - openshift
  - openshift-*
  - syn
  - default
  - '*-production'
  - '*-prod'
  - csl-*
  - kube-system
```

P.S. For security reasons some words have been changed in the above SyncConfig
## Logs

No relevant logs for this issue has been found.

## Expected behavior

Espejo should not create LimitRanges for "csl-*" namespaces.

## To Reproduce

1. Define several namespaces with names that are under these regex definitions:
*   - openshift
    - openshift-*
    - syn
    - default
    - '*-production'
    - '*-prod'
    - csl-*
    - kube-system
2. oc -n \<espejo-namespaces\> apply -f limitranges.yaml
where limitranges.yaml:
```yml
apiVersion: sync.appuio.ch/v1alpha1
kind: SyncConfig
metadata:
  name: limitrange
  namespace: <espejo-namespaces>
spec:
  forceRecreate: true
  namespaceSelector:
    ignoreNames:
    - openshift
    - openshift-*
    - syn
    - default
    - '*-production'
    - '*-prod'
    - csl-*
    - kube-system
    labelSelector:
      matchExpressions:
      - key: name
        operator: Exists
  syncItems:
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: default-limits
    spec:
      limits:
      - default:
          cpu: 500m
          memory: 128Mi
        defaultRequest:
          cpu: 10m
          memory: 32Mi
        type: Container
```

## Environment (please complete the following information):

- Image Version: espejo:v0.3.2
- K8s Version: v1.11.0+d4cacc0
- K8s Distribution: OpenShift
